branches:
  only:
    - master
    - develop
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"
  - "pypy"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libudev-dev gccxml
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script: py.test --junitxml=tests.xml --enable-privileged -rfEsxX -v
